name: Build

on:
    push:
        branches:
            - master
    pull_request:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: true
                  fetch-depth: 0

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: '0.82.0'
                  extended: true

            - name: Clean public directory
              run: rm -rf public

            - name: Build theme
            - uses: c-hive/gha-npm-cache@v1
              run: ./bin/buildTheme.sh

            - name: Build site
              run: hugo

            #- name: Create a CNAME file which mapping to our custom domain
            #  run: cd src/ && echo 'devdocs.prestashop.com' > public/CNAME

            - name: Return to root directory
              run: cd ..

            - name: Deploy
              if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/master' }}
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: public
